### ISSUE TITLE
Website - French Translation

### ISSUE THREAD

**Issue by TraderStf** [BonzaiThePenguin/Loading#12]
Hi,
I have sent an email with the correct French strings and the html page to you by email, perhaps miss it.

For the strings, I have pulled a request.

For the html page, where do you want to receive it ?

**Comment by TraderStf** [comment]
Here it is, available for 28 days, today is may 7.

http://www.fileconvoy.com/dfl.php?id=gc84fd43782baefd3999660253b08bb8061c100519
loading-webpage-FRENCH-v1.html (7.9 Ko)

**Comment by BonzaiThePenguin** [comment]
I got your email although I've been super busy, sorry. I added a new sentence to the website describing a new feature:

```
Clicking the checkbox disables the spinning animation for that app or process.
```

**Comment by TraderStf** [comment]
you are welcome, just checking as my isp is sometimes blacklisted... have a nice day

**Comment by BonzaiThePenguin** [comment]
Alright finally got around to downloading it, thanks!
