### ISSUE TITLE
Update dialog - FR corrections

### ISSUE THREAD

**Issue by TraderStf** [BonzaiThePenguin/Loading#19]
Don't find these strings in github...

Anyway, some will be obsolete... but not the top and bottom area.

don't miss the "...lA télé...":
Loading ### est disponib<b><big>le, vou</b></big>s utilisez la version ###. Voulez-vous l<b>a télécharger pour l'installer</b> maintenant ?
- [ ] Télécharger et installer automatiquement les mises à jour.

<i>FYI ...the "new" update... new is useless, so not added in French.</i>

---

Certains <b>procédés -> processus</b> apparaissent désormais <b>sous l'Notification Center -> comme Centre de notifications</b> , Contacts, <b>Calendar -> Calendrier</b>, ou Flash Player <i> (it is ok, just FYI, FP never translated)</i>
Les cases à cocher pour désactiver l'animation ?????de filature???? sont maintenant affiché<b>e</b>s plus souvent
Chang<b>é -> e</b>le nom du produit pour Loading dans le menu A propos de
Correction d'un problème avec les traductions françaises manquantes
Traductions norvégiennes meilleurs

**Comment by BonzaiThePenguin** [comment]
The software update thing is already obsolete, yeah. I just run those through Google Translate and don't make any attempt to verify their correctness.

**Comment by BonzaiThePenguin** [comment]
I'm gonna close this one. If you have any fixes for the Software Update panel, I think we have to submit those to the Sparkle framework first and then I can pull the changes from there:

https://github.com/sparkle-project/Sparkle
