### ISSUE TITLE
Optionally ignore specific apps/processes, however...

### ISSUE THREAD

**Issue by BonzaiThePenguin** [BonzaiThePenguin/Loading#2]
The actual logic for ignoring the apps/processes is straightforward, but I'm stuck trying to get the NSMenu APIs to do what I want.

Ideally there would be a minimalist checkbox next to an app or process when mousing over the menu item, but I can't use `setView` to add a checkbox since that breaks the keyboard controls, can't use `setState` to add a check mark as that causes the menu to flicker, and can't use custom drawing without proper access to the height of the `CGContextRef`.

The height of the context could be retrieved using `GetPortBounds`, but Apple removed the header files and symbols for QuickDraw from the HIToolbox.framework that's included with the Xcode SDKs. The HIToolbox that's in your `/System/Library/Frameworks` folder has all of the QuickDraw functionality there, since it's still used by the menu APIs, but I can't figure out how to get Xcode to link against that one.

I'm close to just switching to a fake NSWindow-based menu, like Apple did with the old Spotlight menu in Mavericks, or switching to a less-intuitive design just to get _something_ implemented.

**Comment by jmarquis** [comment]
Alternative idea: only show/animate the spinner when the in-focus app is accessing the network — this would be more like the native iOS behavior. I like the idea of ignoring processes too, but this would avoid having to add to the UI.

By the way, thanks for the great work. This is a really neat app!

**Comment by BonzaiThePenguin** [comment]
The Experimental branch contains the UI and option to ignore specific apps. I ended up discovering a magic combination of hacks that let me draw on top of the menu, which I promptly used to draw a checkbox and nothing else.

**Comment by BonzaiThePenguin** [comment]
Build is available here:
http://bonzaiapps.com/loading/Loading_alpha.zip

Only tested it on Yosemite so far, for Retina and non-Retina displays.

**Comment by BonzaiThePenguin** [comment]
Hm, it's a bit broken on OS X 10.7. That's annoying.

**Comment by BonzaiThePenguin** [comment]
Fixed it! Seems to work fine on all versions of OS X now.
