### ISSUE TITLE
Show icon of app most using the network

### ISSUE THREAD

**Issue by BonzaiThePenguin** [BonzaiThePenguin/Loading#27]
‏@soosbird on Twitter suggested adding an icon to the menu for which app is using the network the most at any moment in time:

![ceyezt2ugaaglcy png-large](https://cloud.githubusercontent.com/assets/1899757/7591948/c02584ae-f89e-11e4-9205-0613d6c26969.png)

Thoughts?

**Comment by derhuerst** [comment]
I don't think that's necessary. It's common that on a computer, many apps have heavy network activity at the same time. Therefore I think the purpose of this tool should be to _just_ show _which apps_ are using the internet, not how much they are using it.

**Comment by BonzaiThePenguin** [comment]
Yeah, you're right.
